FROM alpine:3.21.3

LABEL maintainer="VG"
LABEL name="cpp-dev"
LABEL version="latest"

RUN echo '@edge https://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories && \
    echo '@edge https://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    echo '@edge https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    apk -U upgrade && \
    apk add --no-cache \
    git \
    musl-dev \
    gcc \
    libc-dev \
    clang clang-extra-tools \
    lld \
    binutils-dev \
    cmake \
    gdb \
    build-base \
    wget
    # flex \
    # bison \
    # gmp-dev \
    # mpfr-dev \
    # mpc1-dev \
    # isl-dev
    # isl-dev \
    # libexecinfo-dev \
    # update-alternatives

# RUN wget https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.gz && \
#     tar -xvf gcc-14.1.0.tar.gz && \
#     cd gcc-14.1.0 && \
#     ./contrib/download_prerequisites && \
#     mkdir build && \
#     cd build && \
#     ../configure --prefix=/usr/local/gcc-14.1 --enable-languages=c,c++ --disable-multilib && \
#     make -j$(nproc) && \
#     make install && \
#     cd ../.. && \
#     rm -rf gcc-14.1.0.tar.gz gcc-14.1.0

# RUN update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-14.1/bin/gcc 100 && \
#     update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-14.1/bin/g++ 100 && \
#     update-alternatives --set gcc /usr/local/gcc-14.1/bin/gcc && \
#     update-alternatives --set g++ /usr/local/gcc-14.1/bin/g++

# ENV PATH=/usr/local/gcc-14.1/bin:$PATH
# ENV LD_LIBRARY_PATH=/usr/local/gcc-14.1/lib64:$LD_LIBRARY_PATH

WORKDIR /home

RUN git clone https://github.com/resslinux/libexecinfo.git && \
    cd libexecinfo && make && make install && \
    cd .. && rm -rf libexecinfo

WORKDIR /home